postscript("IGD+.Boxplot.eps", horizontal=FALSE, onefile=FALSE, height=8, width=12, pointsize=10)
resultDirectory<-"../data"
qIndicator <- function(indicator, problem)
{
fileNSGAII<-paste(resultDirectory, "NSGAII", sep="/")
fileNSGAII<-paste(fileNSGAII, problem, sep="/")
fileNSGAII<-paste(fileNSGAII, indicator, sep="/")
NSGAII<-scan(fileNSGAII)

fileSPEA2<-paste(resultDirectory, "SPEA2", sep="/")
fileSPEA2<-paste(fileSPEA2, problem, sep="/")
fileSPEA2<-paste(fileSPEA2, indicator, sep="/")
SPEA2<-scan(fileSPEA2)

fileMOEADDRA<-paste(resultDirectory, "MOEADDRA", sep="/")
fileMOEADDRA<-paste(fileMOEADDRA, problem, sep="/")
fileMOEADDRA<-paste(fileMOEADDRA, indicator, sep="/")
MOEADDRA<-scan(fileMOEADDRA)

fileMOEADD<-paste(resultDirectory, "MOEADD", sep="/")
fileMOEADD<-paste(fileMOEADD, problem, sep="/")
fileMOEADD<-paste(fileMOEADD, indicator, sep="/")
MOEADD<-scan(fileMOEADD)

fileAGE-MOEA-II<-paste(resultDirectory, "AGE-MOEA-II", sep="/")
fileAGE-MOEA-II<-paste(fileAGE-MOEA-II, problem, sep="/")
fileAGE-MOEA-II<-paste(fileAGE-MOEA-II, indicator, sep="/")
AGE-MOEA-II<-scan(fileAGE-MOEA-II)

fileESPEA<-paste(resultDirectory, "ESPEA", sep="/")
fileESPEA<-paste(fileESPEA, problem, sep="/")
fileESPEA<-paste(fileESPEA, indicator, sep="/")
ESPEA<-scan(fileESPEA)

fileGWASFGA<-paste(resultDirectory, "GWASFGA", sep="/")
fileGWASFGA<-paste(fileGWASFGA, problem, sep="/")
fileGWASFGA<-paste(fileGWASFGA, indicator, sep="/")
GWASFGA<-scan(fileGWASFGA)

algs<-c("NSGAII","SPEA2","MOEADDRA","MOEADD","AGE-MOEA-II","ESPEA","GWASFGA")
boxplot(NSGAII,SPEA2,MOEADDRA,MOEADD,AGE-MOEA-II,ESPEA,GWASFGA,names=algs, notch = TRUE)
titulo <-paste(indicator, problem, sep=":")
title(main=titulo)
}
par(mfrow=c(3,3))
indicator<-"IGD+"
qIndicator(indicator, "WFG1_2")
qIndicator(indicator, "WFG2_2")
qIndicator(indicator, "WFG3_2")
qIndicator(indicator, "WFG5_2")
qIndicator(indicator, "WFG4_2")
qIndicator(indicator, "WFG6_2")
qIndicator(indicator, "WFG7_2")
qIndicator(indicator, "WFG8_2")
qIndicator(indicator, "WFG9_2")
qIndicator(indicator, "WFG1_3")
qIndicator(indicator, "WFG2_3")
qIndicator(indicator, "WFG3_3")
qIndicator(indicator, "WFG5_3")
qIndicator(indicator, "WFG4_3")
qIndicator(indicator, "WFG6_3")
qIndicator(indicator, "WFG7_3")
qIndicator(indicator, "WFG8_3")
qIndicator(indicator, "WFG9_3")
qIndicator(indicator, "WFG1_5")
qIndicator(indicator, "WFG2_5")
qIndicator(indicator, "WFG3_5")
qIndicator(indicator, "WFG5_5")
qIndicator(indicator, "WFG4_5")
qIndicator(indicator, "WFG6_5")
qIndicator(indicator, "WFG7_5")
qIndicator(indicator, "WFG8_5")
qIndicator(indicator, "WFG9_5")
